[package]
name = "huahcoding_ruc"
version = "0.1.0"
authors = ["samuel14luis <luismendoza.samuel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
